language: node_js
node_js:
  - '11.10.1'
  - '10'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version  1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script: yarn run test
